name: 02 Regression tests with db-sync

on:
  workflow_dispatch:
    inputs:
      node_rev:
        description: "cardano-node revision (default: master HEAD)"
        required: false
      dbsync_rev:
        description: "db-sync revision (default: master HEAD)"
        required: false
      cluster_era:
        type: choice
        description: "Cluster era"
        options:
        - babbage
        default: babbage
      tx_era:
        type: choice
        description: "Tx era"
        options:
        - default
        - babbage
        - alonzo
        - mary
        - allegra
        - shelley
        default: default
      markexpr:
        type: choice
        description: "Selection of tests"
        options:
        - all
        - dbsync
        - smoke
        - plutus
        - plutus and smoke
        - not long
        - dbsync and smoke
        - dbsync and plutus
        - dbsync and not long
        default: dbsync
      topology:
        type: choice
        description: "Network topology"
        options:
        - legacy
        - p2p
        - mixed
        default: legacy
      fast_cluster:
        type: boolean
        default: false
        description: "Start cluster directly in target era"
      testrun_name:
        required: false
        description: "Test run name (internal)"
      skip_passed:
        type: boolean
        default: false
        description: "Skip tests that already passed (internal)"

run-name: ${{ inputs.testrun_name && 'Run:' || ''}} ${{ inputs.testrun_name }} ${{ (inputs.testrun_name && inputs.skip_passed) && ':repeat:' || '' }}

jobs:
  regression_tests:
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      node_rev: ${{ inputs.node_rev }}
      dbsync_rev: ${{ inputs.dbsync_rev }}
      cluster_era: ${{ inputs.cluster_era }}
      tx_era: ${{ inputs.tx_era }}
      markexpr: ${{ inputs.markexpr }}
      topology: ${{ inputs.topology }}
      enable_dbsync: true
      fast_cluster: ${{ inputs.fast_cluster }}
      testrun_name: ${{ inputs.testrun_name }}
      skip_passed: ${{ inputs.skip_passed }}
      env-path: .github/env_regression_dbsync
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TCACHE_BASIC_AUTH: ${{ secrets.TCACHE_BASIC_AUTH }}
      TCACHE_URL: ${{ secrets.TCACHE_URL }}
