name: db-sync regression tests

on:
  workflow_dispatch:
    inputs:
      tests_rev:
        description: "cardano-node-tests revision (default: HEAD)"
        required: false
      node_rev:
        description: "cardano-node revision (default: HEAD)"
        required: false
      node_branch:
        description: "cardano-node branch (default: master)"
        required: false
      dbsync_rev:
        description: "db-sync revision (default: HEAD)"
        required: false
      dbsync_branch:
        description: "db-sync branch (default: master)"
        required: false
      cluster_era:
        type: choice
        description: "Cluster era"
        options:
        - babbage
        - alonzo
        default: alonzo
      tx_era:
        type: choice
        description: "Tx era (uses default Tx era when empty)"
        options:
        - ""
        - babbage
        - alonzo
        - mary
        - allegra
        - shelley
        default: ""
      cddl_format:
        type: boolean
        default: false
        description: "Use CDDL format for Tx body"
      skip_long:
        type: boolean
        default: false
        description: "Skip long running tests"

jobs:
  dbsync_regression:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the Buildkite pipeline - run db-sync regression tests
        uses: zegocover/buildkite-pipeline-action@master
        with:
          access_token: "${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}"
          pipeline: "input-output-hk/cardano-node-tests-dbsync"
          commit: "${{ github.event.inputs.tests_rev }}"
          message: ":github: Triggered by GitHub Action"
          env: '{
          "NODE_REV":"${{ github.event.inputs.node_rev }}",
          "NODE_BRANCH":"${{ github.event.inputs.node_branch }}",
          "DBSYNC_REV":"${{ github.event.inputs.dbsync_rev }}",
          "DBSYNC_BRANCH":"${{ github.event.inputs.dbsync_branch }}",
          "CLUSTER_ERA":"${{ github.event.inputs.cluster_era }}",
          "TX_ERA":"${{ github.event.inputs.tx_era }}",
          "USE_CDDL":"${{ github.event.inputs.cddl_format }}",
          "CI_SKIP_LONG":"${{ github.event.inputs.skip_long }}"
          }'
